addons:
    apt:
        packages:
        - dos2unix
cache:
- pip
dist: xenial
env:
  global:
    - secure: m1buinL/51/kTLAlSm02/RMk7iIOclOdDYHTataV8v6u0AqMhsRV1myGNXNdjnFIK2nn/3Hu/8EdGGXyOFrl8GR/T3M8/y3d2ifQlx7vzb4earzr3OBhWQC4+JbBvx1M05CirPt3jof8+j/bx48g1s5Cq24qqFRaOmKS80OYqfFKAWd8stdEnd9MQmSWLe7uf1AY4nxNzadh/S9pZS1AmJWPbPq0D0LQkQHfRDw0bxm5E/ZLcMCTsXWMNSNl/NATP5fX25whm/j46boC2dRy8MivKtUi234PMTYraIol/NFDPAcs71zr4qUVVwQTsRWL4xhCuRcMnLyqVKquy6wQZs9RVsVImmYPtC5+5Z44aRTzN3IFYyyuOnbXHDccEVOsyXgvm+uoCppyWk1GO2WIUCf17PA5Q9EYt6/5tkI4yfwqNMcg7LhyWZcAbtW4ZEY9h4zqwT+7+jH5747OvH1808wCc0JvkV/QGCsiffSVX7KeeCez3yYuUkW3+7UK/t24W6xS1Y7S6G6d36Lh6HBJ0c9fVBeJ5G1XswUjsLTffgIekBXGVfkvgWPzppPcnA8XCLwSCxM/yIck8B2sBtBQs/JKI7nolqQ7x+D3i0dxfg4rN9D/9wM9f5d0Gb9rsW5DeL/ImQtir6nP2012PrkgSkPkxr5hTJQHXMbc1C2VGbA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/blackweb
    - GIT_BRANCH: master
    - TZ:       Africa/Johannesburg
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

sudo: required

install:
  - pip3 install --upgrade pip
  - pip3 install PyFunceble
  - pip3 install ultimate-hosts-blacklist-whitelist

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  - bash dev-tools/data-testing.sh

notifications:
  on_success: never
  on_failure: always
